import type { Product } from '@/shared/types/product'

export const mockProducts: Product[] = [
	{
		id: '1',
		slug: 'classic-hoodie',
		title: 'Classic Hoodie',
		description: 'Heavyweight 380 gsm hoodie. Back print, oversize fit.',
		price: 4900,
		images: [
			'/image/hoodie.jpg',
			'/image/stickers.jpg',
			'/image/tee-black.jpg',
			'/image/longsleeve.jpg',
		],
		sizes: ['S', 'M', 'L', 'XL'],
		inStock: true,
		createdAt: '2026-09-01T10:00:00Z',
	},
	{
		id: '2',
		slug: 'tee-white',
		title: 'Tee White',
		description: '100% cotton, 220 gsm. Front print.',
		price: 2200,
		images: [
			'/image/tee-white.jpg',
			'/image/cap.jpg',
			'/image/hoodie.jpg',
			'/image/tee-black.jpg',
			'/image/stickers.jpg',
		],
		sizes: ['S', 'M', 'L', 'XL', 'XXL'],
		inStock: true,
		createdAt: '2026-09-01T10:00:00Z',
	},
	{
		id: '3',
		slug: 'logo-cap',
		title: 'Logo Cap',
		description: 'Cap with embroidered logo. One size.',
		price: 1800,
		images: ['/image/cap.jpg', '/image/tee-white.jpg', '/image/longsleeve.jpg'],
		sizes: [],
		inStock: true,
		createdAt: '2026-09-01T10:00:00Z',
	},
	{
		id: '4',
		slug: 'sticker-pack',
		title: 'Sticker Pack',
		description: 'Set of 5 vinyl stickers.',
		price: 600,
		images: [
			'/image/stickers.jpg',
			'/image/hoodie.jpg',
			'/image/cap.jpg',
			'/image/tee-black.jpg',
		],
		sizes: [],
		inStock: true,
		createdAt: '2026-09-01T10:00:00Z',
	},
	{
		id: '5',
		slug: 'tee-black',
		title: 'Tee Black',
		description: 'Same base, black. Front print.',
		price: 2200,
		images: [
			'/image/tee-black.jpg',
			'/image/longsleeve.jpg',
			'/image/tee-white.jpg',
			'/image/stickers.jpg',
			'/image/hoodie.jpg',
		],
		sizes: ['S', 'M', 'L', 'XL'],
		inStock: true,
		createdAt: '2026-09-01T10:00:00Z',
	},
	{
		id: '6',
		slug: 'longsleeve',
		title: 'Longsleeve',
		description: 'Long sleeve with back print. 100% cotton.',
		price: 2900,
		images: ['/image/longsleeve.jpg', '/image/tee-black.jpg', '/image/cap.jpg'],
		sizes: ['S', 'M', 'L', 'XL'],
		inStock: true,
		createdAt: '2026-09-01T10:00:00Z',
	},
]
